# Generated by Django 3.0.7 on 2020-06-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200627_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token_code',
            new_name='activation_token_code',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='token_expiration',
            new_name='activation_token_expiration',
        ),
        migrations.AddField(
            model_name='profile',
            name='forget_password_token_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='forget_password_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
