# Generated by Django 3.0.8 on 2020-07-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_token_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token_secret',
        ),
        migrations.AddField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='X4K1hh2ycgrDdassBUIFBNhApDjHpxd4p8ftCfS4', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='Lohhof2Zto0Wr7H49BAYXhFa5Rq1f04TnsFcb4T0', max_length=50),
        ),
    ]
