# Generated by Django 3.0.8 on 2020-07-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200723_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='dBy8yFXH4T77hZoe6BPQ0rJ0BppZvjDADhAmw3G4', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='bCLpl0NKZMuVGcTarLtzb8eIhmvNLS0FsbArtF0O', max_length=50),
        ),
    ]
