# Generated by Django 3.0.8 on 2020-08-16 19:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200723_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='myarr',
        ),
        migrations.AddField(
            model_name='profile',
            name='get_mail_about_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_viewer',
            field=models.CharField(choices=[('o', 'only me'), ('r', 'related'), ('p', 'public')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchable_group',
            field=models.CharField(choices=[('o', 'only me'), ('r', 'related'), ('p', 'public')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='JwYE6b4NGTuDVnrZof9LzAGq5OCiIxKfXznVUP1K', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='colleges',
            field=api.models.MyArrayField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degrees',
            field=api.models.MyArrayField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emails',
            field=api.models.MyArrayField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_numbers',
            field=api.models.MyArrayField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[api.models.validate_image], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='ag0xXBLK2y543fjSKFrNVVnAp2bp79sj9auWcipI', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='schools',
            field=api.models.MyArrayField(blank=True, max_length=300, null=True),
        ),
    ]
