# Generated by Django 3.0.8 on 2020-08-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200816_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='4vM6YIXPYFoC2zm0LWUhROFdDm1NebV6Tz9KXU2e', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_viewer',
            field=models.CharField(choices=[('only me', 'only me'), ('related', 'related'), ('public', 'public')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='18hRPoOb27hXJhTbQIBHSisODx1PB1aZjX54Vj7b', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='searchable_group',
            field=models.CharField(choices=[('only me', 'only me'), ('related', 'related'), ('public', 'public')], default='public', max_length=20),
        ),
    ]
