# Generated by Django 3.0.8 on 2020-08-22 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20200816_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='JoD1DM4RAyWetHgN4CAeS7i4miYt5nSzUYxqH0QO', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_viewer',
            field=models.CharField(choices=[('Only Me', 'Only Me'), ('Related', 'Related'), ('Public', 'Public')], default='Public', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='F6qvX8ajh0WoHio1A3ynQJjaanUjdlAxrRHVa6yO', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='searchable_group',
            field=models.CharField(choices=[('Only Me', 'Only Me'), ('Related', 'Related'), ('Public', 'Public')], default='Public', max_length=10),
        ),
        migrations.CreateModel(
            name='Staffmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('viewers', models.CharField(choices=[('Admins', 'Admins'), ('Selected', 'Selected'), ('Public', 'Public')], default='Public', max_length=10)),
                ('admins', models.ManyToManyField(related_name='admin_staffmaps', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_staffmaps', to=settings.AUTH_USER_MODEL)),
                ('viewable_to', models.ManyToManyField(blank=True, related_name='viewble_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('viewers', models.CharField(choices=[('Admins', 'Admins'), ('Selected', 'Selected'), ('Public', 'Public')], default='Public', max_length=10)),
                ('admins', models.ManyToManyField(related_name='admin_clans', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_clans', to=settings.AUTH_USER_MODEL)),
                ('viewable_to', models.ManyToManyField(blank=True, related_name='viewable_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
