# Generated by Django 3.0.8 on 2020-08-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200822_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='oMbRuoRvodYp5RD59YcoNJV87Y0Sv5FB3kB9D2HE', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='NrJex45SY0rCqP0gGw4X168dN0RcaLkd6S49EfwK', max_length=50),
        ),
        migrations.CreateModel(
            name='ClanPersonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='api.Clan')),
                ('first_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_persons', to='api.Person')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clanpersons', to='api.Relation')),
                ('second_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_persons', to='api.Person')),
            ],
        ),
    ]
