# Generated by Django 3.0.8 on 2020-08-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200822_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='tree_type',
            field=models.CharField(choices=[('Family_Clan', 'Family_Clan')], default='Family_Clan', max_length=15),
        ),
        migrations.AddField(
            model_name='staffmap',
            name='tree_type',
            field=models.CharField(choices=[('Staffmap', 'Staffmap')], default='Staffmap', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='ScE6bCNbKIUgLZgoKw3VnM8BasFl3helHY8WUlk6', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='eySP1D5vTCPNhsh4DdHd41X15A4o0N5FDbUIvEC4', max_length=50),
        ),
    ]
