# Generated by Django 3.0.8 on 2020-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200823_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='tree_type',
        ),
        migrations.RemoveField(
            model_name='staffmap',
            name='tree_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='BLCsVdwyo8H4zdbGEZsNfImHsQ31Kn4bgAq95ixK', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='Np17xbaxIVn6EE5K5UuEMQOFbBnVlWBNSS8K4Hhh', max_length=50),
        ),
    ]
