# Generated by Django 3.0.8 on 2020-08-26 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_auto_20200823_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_clans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='LwwNLXm5xCmaIBXhuE52sjMIndSz5kVDe1ZA2VIc', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='AtF2007e43uwwLaJR77KKMV1xjzQBew2Ca8ZLHUi', max_length=50),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='staffmap',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_staffmaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
