# Generated by Django 3.0.8 on 2020-08-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200826_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_token_secret',
            field=models.CharField(default='AhyUNHHVRPxoVadLLTYB6RqGt6zwDFhGIVUpXg19', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token_secret',
            field=models.CharField(default='tXn6rO2C9kO8aSJXo11vM7Y6x0VMBAWjYz7325Lf', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='relationcalc',
            unique_together={('first_relation', 'second_relation')},
        ),
    ]
